spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/plane_flights
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

aviationstack:
  base-url: "https://api.aviationstack.com/v1"
  access-key: "${ACCESS_KEY}"
